/*
 * Copyright (C) CoolKidsKassa, Inc - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Written by Leslie Lauw <18151167> and Dennis van Waas <18>, October 2018
 * The Netherlands - The Hague University 
 * Class: 2B 
 * Group: 09 
 */
package kassaopdracht;



import java.text.DecimalFormat;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;



/**
 *
 * @author L.A, D.W
 */
public class KassaOpdracht extends javax.swing.JDialog {
    
    public static int countPizza;
    public static int countPatat;  
    public static int countSnoep;
    public static int countKaas;
    public static int countBier;
    public static int countFruit;
    public static double tussenPrijs;
    public static boolean kortingToepassen;
    public static JTextArea textarea;
    public static double subtotaal;
    public static double kortingSubtotaal;
    public static double btwSubtotaal;
    public static double totaalPrijs;
    public static double totaalPrijsGeenKorting;
    private static DecimalFormat df2 = new DecimalFormat(".##");

    
    
    public static  double [] prijzenArray(){
        double [] prijzenProducten;
        
               prijzenProducten = new double [7];
               prijzenProducten [0] = 6.00;
               prijzenProducten [1] = 2.25;
               prijzenProducten [2] = 2.00;
               prijzenProducten [3] = 1.50;
               prijzenProducten [4] = 2.90;
               prijzenProducten [5] = 3.50;
               
               
       return (prijzenProducten);
    }
    
    public static double tussenPrijzen (){
        
        
        double [] prijzenProducten1;
        prijzenProducten1 = prijzenArray();
        
        tussenPrijs = 
                ((countPizza * prijzenProducten1 [0]) + (countPatat * prijzenProducten1 [1]) + (countSnoep * prijzenProducten1 [2]) + 
                (countKaas * prijzenProducten1 [3]) + (countBier * prijzenProducten1 [4]) + (countFruit * prijzenProducten1[5]));
                
        return tussenPrijs;
    } 


    
    
    /**
     * Creates new form test2
     */
    public KassaOpdracht(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setTitle("  CoolKidsKassa                                                                                by Leslie Lauw & Dennis van Waas 2B09");

        jButton1.setText("Pizza");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Patat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Snoep");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("AFREKENEN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Kaas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Bier");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Fruit");
        jButton7.setToolTipText("");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Merriweather", 1, 36)); // NOI18N

        jLabel1.setText("CoolKidsKassa");
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);

        jToggleButton1.setText("Korting");
        jToggleButton1.setBackground(new java.awt.Color(51, 255, 51));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText(String.valueOf(tussenPrijs));
        jTextField1.setFocusable(false);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jToggleButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {  
        
        int input = Integer.parseInt(JOptionPane.showInputDialog("Gekozen product: Pizza. Voer de hoeveelheid in"));
        countPizza = countPizza + input;
        JOptionPane.showMessageDialog(null, "U heeft er " + input + " toegevoegd aan uw winkelwagentje");
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int input = Integer.parseInt(JOptionPane.showInputDialog("Gekozen product: Patat. Voer de hoeveelheid in"));
        countPatat = countPatat + input;
        JOptionPane.showMessageDialog(null, "U heeft er " + input + " toegevoegd aan uw winkelwagentje");
        
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int input = Integer.parseInt(JOptionPane.showInputDialog("Gekozen product: Snoep. Voer de hoeveelheid in"));
        countSnoep= countSnoep + input;
        JOptionPane.showMessageDialog(null, "U heeft er " + input + " toegevoegd aan uw winkelwagentje");
        
    }                                        

    public void jButton4ActionPerformed(java.awt.event.ActionEvent evt   ) {  
                double [] prijzenProducten2;
                prijzenProducten2 = prijzenArray();
        Object[] options1 = {"Reset"};
        

        JPanel panel = new JPanel();
        panel.add(new JLabel("Bon"));
        textarea = new JTextArea (15,20);
        textarea.setFocusable(false);
        panel.add(textarea);

        
        subtotaal = tussenPrijzen();
        kortingSubtotaal = tussenPrijzen() * 0.10;
        btwSubtotaal = tussenPrijzen() * 0.06;
        double btwOutput = btwSubtotaal;

        totaalPrijs = tussenPrijzen() + kortingSubtotaal + btwSubtotaal;
        double totaalPrijsOutput = totaalPrijs;
        totaalPrijsGeenKorting = tussenPrijzen() + btwSubtotaal;
        double totaalPrijsGeenKortingOutput = totaalPrijsGeenKorting;
       

        if (kortingToepassen ==true){
        textarea.setText(
                (countPizza + "       Pizza" + "            € " + df2.format(countPizza * prijzenProducten2[0]))+ "\n"+
                (countPatat + "       Patat" + "            € " + df2.format(countPizza * prijzenProducten2[1]))+ "\n"+ 
                (countSnoep + "       Snoep" + "         € " + df2.format(countSnoep * prijzenProducten2[2]))+ "\n"+
                (countKaas + "       Kaas" + "           € " + df2.format(countKaas * prijzenProducten2[3]))+ "\n"+
                (countBier + "       Bier" + "              € " + df2.format(countBier * prijzenProducten2[4]))+ "\n"+
                (countFruit + "       Fruit" + "             € " + df2.format(countFruit * prijzenProducten2[5])) + "\n"+
                 "\n"+
                 "\n"+
                "Subtotaal    "+ "          € " + subtotaal + "\n" +
                 "\n"+
                "Korting 10%       € " + df2.format(kortingSubtotaal) + "\n"+
                 "\n"+
                "BTW 6%            € " + df2.format(btwOutput) + "\n"+
                 "\n"+
                "Totale Prijs         € " + df2.format(totaalPrijsGeenKortingOutput)
                );
      
        }else {
        textarea.setText(
                (countPizza + "       Pizza" + "            € " + df2.format(countPizza * prijzenProducten2[0]))+ "\n"+
                (countPatat + "       Patat" + "            € " + df2.format(countPizza * prijzenProducten2[1]))+ "\n"+ 
                (countSnoep + "       Snoep" + "         € " + df2.format(countSnoep * prijzenProducten2[2]))+ "\n"+
                (countKaas + "       Kaas" + "           € " + df2.format(countKaas * prijzenProducten2[3]))+ "\n"+
                (countBier + "       Bier" + "             € " + df2.format(countBier * prijzenProducten2[4]))+ "\n"+
                (countFruit + "       Fruit" + "            € " + df2.format(countFruit * prijzenProducten2[5])) + "\n"+
                 "\n"+
                 "\n"+
                "Subtotaal    "+ "          € " + subtotaal + "\n" +
                 "\n"+
                "Geen Korting       € 0.00" + "\n" +
                 "\n"+
                "BTW 6%            € " + df2.format(btwOutput) + "\n"+
                 "\n"+
                "Totale Prijs         € " + df2.format(totaalPrijsOutput)
                );
        
        

        }
        
   int result = JOptionPane.showOptionDialog(null, panel, "Het Bonnetje",
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options1, null);

      if (result == JOptionPane.YES_OPTION){
          countPizza = 0;
          countPatat = 0;
          countSnoep = 0;
          countKaas = 0;
          countBier = 0;
          countFruit= 0;
          JOptionPane.showMessageDialog(null, "Volgende Klant!");
      }
  
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        int input = Integer.parseInt(JOptionPane.showInputDialog("Gekozen product: Kaas. Voer de hoeveelheid in"));
        countKaas = countKaas + input;
        JOptionPane.showMessageDialog(null, "U heeft er " + input + " toegevoegd aan uw winkelwagentje");
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        int input = Integer.parseInt(JOptionPane.showInputDialog("Gekozen product: Bier. Voer de hoeveelheid in"));
        countBier = countBier + input;
        JOptionPane.showMessageDialog(null, "U heeft er " + input + " toegevoegd aan uw winkelwagentje");
        
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        int input = Integer.parseInt(JOptionPane.showInputDialog("Gekozen product: Fruit. Voer de hoeveelheid in"));
        countFruit = countFruit + input;
        JOptionPane.showMessageDialog(null, "U heeft er " + input + " toegevoegd aan uw winkelwagentje");

        

    }                                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }   
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        kortingToepassen = false;
        jToggleButton1.setBackground(new java.awt.Color(51, 255, 51));
        if (jToggleButton1.isSelected()){
            kortingToepassen = true;
            JOptionPane.showMessageDialog(null, "Korting Toegepast!");
            jToggleButton1.setText("Korting AAN!");
            jToggleButton1.setBackground(new java.awt.Color(51, 255, 51));
        
        }else {
            jToggleButton1.setBackground(new java.awt.Color(255, 0, 0));
            kortingToepassen = false;
            jToggleButton1.setText("Korting UIT!");
            JOptionPane.showMessageDialog(null, "Korting UIT!");
        }
       
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KassaOpdracht dialog = new KassaOpdracht(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                        
                    }
                });
                dialog.setVisible(true);
                
            }
        });
        

        
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration                   
}



